<?php

/* ScSegmentation */

class ScSegment extends ObjectModel
{
    public $id;
    public $name;
    public $type;
    public $auto_file;
    public $auto_params;
    public $access;
    public $description;
    public $id_parent;
    public $position;

    protected $tables = array('sc_segment');

    protected $table = 'sc_segment';
    protected $identifier = 'id_segment';

    public function getFields()
    {
        parent::validateFields();
        $fields['name'] = ($this->name);
        $fields['type'] = ($this->type);
        $fields['auto_file'] = ($this->auto_file);
        $fields['auto_params'] = ($this->auto_params);
        $fields['access'] = ($this->access);
        $fields['description'] = ($this->description);
        $fields['id_parent'] = (int) $this->id_parent;
        $fields['position'] = (int) $this->position;

        return $fields;
    }

    public function add($auto_date = true, $null_values = false)
    {
        $this->name = pSQL($this->name);

        return parent::add($auto_date, $null_values); // TODO: Change the autogenerated stub
    }

    public function update($null_values = false)
    {
        $this->name = pSQL($this->name);

        return parent::update($null_values); // TODO: Change the autogenerated stub
    }
}
