{*
 * Copyright ETS Software Technology Co., Ltd
 *
 * NOTICE OF LICENSE
 *
 * This file is not open source! Each license that you purchased is only available for 1 website only.
 * If you want to use this file on more websites (or projects), you need to purchase additional licenses.
 * You are not allowed to redistribute, resell, lease, license, sub-license or offer our resources to any third party.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future.
 *
 * @author ETS Software Technology Co., Ltd
 * @copyright  ETS Software Technology Co., Ltd
 * @license    Valid for 1 website (or project) for each purchase of license
*}
Introduce our website to your friends, get <b>$2</b> in reward when your friend register their account. <br/>Build up your sale network and earn attractive <b>commission</b> for every order generated by your friends (Multi-level marketing). <br/>Your reward can be withdrawn to your bank account, pay for your orders or convert into voucher code. <br/>Your friend will also receive a voucher code worth <b>$10</b> to shop on our website.