<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Polyfill\\Apcu\\' => array($vendorDir . '/symfony/polyfill-apcu'),
    'Symfony\\Component\\Cache\\' => array($vendorDir . '/symfony/cache'),
    'Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'Payline\\' => array($vendorDir . '/monext/payline-sdk/src/Payline'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
);
