<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWYlQ9O5\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWYlQ9O5/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWYlQ9O5.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWYlQ9O5\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerWYlQ9O5\appAppKernelDevDebugContainer([
    'container.build_hash' => 'WYlQ9O5',
    'container.build_id' => 'bf4c2c48',
    'container.build_time' => 1747995315,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWYlQ9O5');
